---
sidebar: sidebar 
permalink: scpivs44_minimum_vcenter_privileges_required.html 
keywords:  
summary: Avant de commencer le déploiement du plug-in SnapCenter pour VMware vSphere, assurez-vous de disposer du minimum de privilèges vCenter requis. 
---
= Privilèges vCenter minimum requis
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Avant de commencer le déploiement du plug-in SnapCenter pour VMware vSphere, assurez-vous de disposer du minimum de privilèges vCenter requis.



== Privilèges requis pour le rôle d'administrateur vCenter

System.Anonyme System.View System.Read datastore.Renommer datastore.Move datastore.Delete datastore.Browse datastore.FileManagement datastore.AllocateSpace Network.assigner Host.Config.Storage Host.Config.Virtual-al-Virtual machine.Remer_al_Exal_al_Virtual machine.Repeautre.Virtual machine.Alpeautre.Virtual machine.Virtual_Exal_Exal_Exal_Exal_Exal_Exal_Exal_Exal_Exal_Exal_Exal_Exal_Exal_Exal_Exal_Exal_Exal_Exal_are_Exal_Exal_are_ar_ar_ar_ar_Alpeautre.machine.Repeautre.machine.Virtual machine.Repeautre.Alpeautre.Virtual machine.Alpeautre.Alpeautre.Alpeautre.Alpeautre.Alpeautre.Alpeautre.Alpeautre.Alpeautre.Alpeautre.Alpeautre.Alpeautre.Alpeautre.Alpe_Virtual machine.Virtual machine.Virtual machine.Alpeautre.Alpeautre.Alpeautre.Alpeautre.



== Privilèges requis spécifiques au plug-in SnapCenter pour VMware vCenter

|===


| *Privilèges* | *Étiquette* 


| Fichier de restauration.netappSCV.Guest | Restauration de fichiers invités 


| Montage du distributeur auxiliaire à récupération.netappDist | Monter/démonter 


| NetappSCV.Backup.DeleteBackupJob | Supprimer le groupe de ressources/sauvegarde 


| NetappSCV.Configure.ConfigenceStorageSystems.Delete | Supprimer les systèmes de stockage 


| Vue du distributeur sélectif de NetApp | Afficher 


| NetappSCV.Recovery.Recovery VM | Restaurer la machine virtuelle 


| NetappSCV.Configure.ConfigureStorageSystems.AddUpdate | Ajouter/Modifier des systèmes de stockage 


| NetappSCV.Backup.BackupNow | Sauvegarder maintenant 


| NetappSCV.invité.configurer | Configuration invité 


| NetappSCV.Configure.ConfigtureSnapCenterServer | Configurez SnapCenter Server 


| Programmée pour le distributeur sélectif de NetApp. Sauvegarde | Créer un groupe de ressources 
|===