---
sidebar: sidebar 
permalink: scpivs44_unmount_a_backup.html 
keywords:  
summary: 'Vous pouvez démonter une sauvegarde lorsque vous n"avez plus besoin d"accéder aux fichiers du datastore.' 
---
= Démonter une sauvegarde
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez démonter une sauvegarde lorsque vous n'avez plus besoin d'accéder aux fichiers du datastore.

Si une sauvegarde est répertoriée comme montée dans l'interface utilisateur du client VMware vSphere, mais qu'elle n'est pas répertoriée dans l'écran de démontage de la sauvegarde, vous devez utiliser l'API REST. `/backup/{backup-Id}/cleanup` pour nettoyer les banques de données hors limites, puis réessayer la procédure de démontage.

Si vous tentez de monter une copie de sauvegarde d'une banque de données NFS sur une machine virtuelle de stockage (SVM) avec le volume racine dans une relation de miroir de partage de charge et que vous risquez de rencontrer l'erreur `You might have reached the maximum number of NFS volumes configured in the vCenter. Check the vSphere Client for any error messages.` Pour éviter ce problème, modifiez le paramètre de volumes maximum en accédant à *ESX* > *Gérer* > *Paramètres* > *Paramètres système avancés* et en modifiant la valeur NFS.MaxVolumes.  La valeur maximale est 256.

.Étapes
. Sur la page des raccourcis client VMware vSphere, sélectionnez *Storage*.
. Dans le volet gauche du navigateur, cliquez avec le bouton droit de la souris sur un datastore, puis sélectionnez *SnapCenter Plug-in pour VMware vSphere* dans la liste déroulante, puis sélectionnez *Unmount* dans la liste déroulante secondaire.
+

IMPORTANT: Assurez-vous de sélectionner le datastore approprié à démonter. Sinon, vous pourriez avoir un impact sur le travail de production.

. Dans la boîte de dialogue *démonter le datastore cloné*, sélectionnez un datastore, cochez la case *démonter le datastore cloné*, puis sélectionnez *démonter*.

