---
sidebar: sidebar 
permalink: scpivs44_rest_api_workflows__modify_built-in_schedules.html 
keywords:  
summary: 'Pour modifier les planifications intégrées pour les tâches client Web VMware vSphere à l"aide du plug-in SnapCenter pour API REST VMware vSphere, vous devez suivre la séquence prescrite d"appels de l"API REST.' 
---
= Workflow d'API REST pour modifier les plannings intégrés
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Pour modifier les planifications intégrées pour les tâches client Web VMware vSphere à l'aide du plug-in SnapCenter pour API REST VMware vSphere, vous devez suivre la séquence prescrite d'appels de l'API REST.

Les planifications intégrées sont les planifications fournies dans le cadre du produit ; par exemple, le planning de vidage de la base de données MySQL. Vous pouvez modifier les plannings suivants :
`Schedule-DatabaseDump`
`Schedule-PurgeBackups`
`Schedule-AsupDataCollection`
`Schedule-ComputeStorageSaving`
`Schedule-PurgeJobs`

Pour chaque API REST, ajoutez `https://<server>:<port>` Au niveau de l'API REST, pour former un terminal complet.

|===
| Étape | API REST | Commentaires 


| 1 | `/4.1/schedules` | `Get all built-in` les programmes obtient une liste des programmes de travaux qui ont été fournis à l'origine dans le produit. Notez le nom de planification que vous souhaitez modifier et l'expression cron associée. 


| 2 | `/4.1/schedules` | `Modify any built-in schedule` modifie le planning nommé. Passez le nom de la planification de l'étape 1 et créez une nouvelle expression cron pour la planification. 
|===