---
sidebar: sidebar 
permalink: scpivs44_minimum_ontap_privileges_required.html 
keywords:  
summary: Les privilèges minimum ONTAP requis varient en fonction des plug-ins SnapCenter utilisés pour la protection des données. 
---
= Privilèges ONTAP requis
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les privilèges minimum ONTAP requis varient en fonction des plug-ins SnapCenter utilisés pour la protection des données.


NOTE: À partir du plug-in SnapCenter pour VMware (SCV) 5.0, vous devez ajouter des applications de type HTTP et ONTAPI comme méthodes de connexion utilisateur pour tous les utilisateurs ONTAP disposant d'un accès personnalisé basé sur les rôles au SCV. Sans accès à ces applications, les sauvegardes échoueront. Vous devez redémarrer le service SCV pour reconnaître les modifications apportées aux méthodes de connexion utilisateur ONTAP.



== Privilèges minimum ONTAP requis

Tous les plug-ins SnapCenter requièrent les privilèges minimaux suivants :

|===


| Commandes de All-Access : ONTAP Privileges minimum. 


| event generate-autosupport-log 


| l'historique des tâches s'affiche
affichage du travail
fin de la tâche 


| lun create lun delete lun igroup add lun igroup create lun igroup delete lun igroup rename lun igroup show lun mapping add-reporting-nodes lun mapping create lun mapping create lun mapping delete lun mapping delete-reporting-nodes lun mapping show lun modify lun move-in-volume lun offline lun lun en ligne lun persistent-reservation clear lun resize série affichage de la lun 


| snapmirror liste-destinations snapmirror add-règle snapmirror règle modification-règle snapmirror règle suppression-règle snapmirror règle snapmirror show snapmirror restore snapmirror show-show-history snapmirror mise à jour de snapmirror snapmirror update-ls-set 


| Version 


| Clone de volume créer clone de volume show volume clone split volume clone split status volume clone split stop volume create volume delete volume delete volume clone fichier clone create volume show-disk-usage volume offline volume online volume volume volume Managed SnapLock-feature modifier volume qtree créer volume qtree supprimer volume qtree modifier volume qtree modifier volume snapshot volume show volume snapshot volume snapshot show volume snapshot volume volume expiration show volume 


| vserver vserver cifs vserver vserver vserver vserver cifs share create vserver cifs share delete vserver cifs shadowcopy show vserver cifs share show vserver cifs show vserver export-policy vserver vserver export-policy create vserver export-policy delete vserver export-policy rule create vserver export-policy rule show vserver export-policy show nvme subsystem nvme host policy show nvme subsystem nvme host policy show nvme subsystem nvme host system connection show nvme system vserver system vserver system vgme system 
|===
|===
| Commandes en lecture seule : ONTAP Privileges minimum 


| l'identité du cluster show network interface show vserver peer vserver show 
|===
|===
| Commandes de All-Access : ONTAP Privileges minimum 


| unité de stockage du groupe de cohérence show 
|===
Vous pouvez ignorer la commande _cluster Identity show_ cluster level lors de la création d'un rôle à associer au vServer de données.


NOTE: Vous pouvez ignorer les messages d'avertissement concernant les commandes vServer non prises en charge.



== Autres informations sur ONTAP

* Vous avez besoin de ONTAP 9.12.1 ou de versions ultérieures pour utiliser la fonctionnalité de synchronisation active de SnapMirror.
* Pour utiliser la fonction d'instantané inviolable (TPS) :
+
** ONTAP 9.13.1 et versions ultérieures sont nécessaires pour SAN
** ONTAP 9.12.1 et versions ultérieures sont nécessaires pour NFS


* Pour NVMe over TCP et le protocole NVMe over FC, vous avez besoin de ONTAP 9.10.1 et versions ultérieures.



NOTE: À partir de la version 9.11.1 ONTAP , la communication avec le cluster ONTAP s'effectue via les API REST.  L'utilisateur ONTAP doit avoir l'application http activée.  Cependant, si des problèmes sont détectés avec les API REST ONTAP , la clé de configuration « FORCE_ZAPI » facilite le passage au flux de travail ZAPI traditionnel.  Vous devrez peut-être ajouter ou mettre à jour cette clé à l'aide des API de configuration et la définir sur true.  Se référer à l'article de la base de connaissances, https://kb.netapp.com/mgmt/SnapCenter/How_to_use_RestAPI_to_edit_configuration_parameters_in_SCV["Comment utiliser RestAPI pour modifier les paramètres de configuration dans SCV"] pour plus d'informations.
