---
sidebar: sidebar 
permalink: scpivs44_disable_and_enable_plugin.html 
keywords:  
summary: 'Si vous n"avez plus besoin des fonctionnalités de protection des données SnapCenter, vous devez modifier la configuration du plug-in SnapCenter pour VMware vSphere. Par exemple, si vous avez déployé le plug-in dans un environnement de test, vous devrez peut-être désactiver les fonctionnalités SnapCenter de cet environnement et les activer dans un environnement de production.' 
---
= Désactivation et activation du plug-in SnapCenter pour VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si vous n'avez plus besoin des fonctionnalités de protection des données SnapCenter, vous devez modifier la configuration du plug-in SnapCenter pour VMware vSphere. Par exemple, si vous avez déployé le plug-in dans un environnement de test, vous devrez peut-être désactiver les fonctionnalités SnapCenter de cet environnement et les activer dans un environnement de production.

.Avant de commencer
* Vous devez disposer des privilèges d'administrateur.
* Assurez-vous qu'aucun travail SnapCenter n'est en cours d'exécution.


.Description de la tâche
Lorsque vous désactivez le plug-in SnapCenter pour VMware vSphere, tous les groupes de ressources sont suspendus et le plug-in n'est pas enregistré en tant qu'extension dans vCenter.

Lorsque vous activez le plug-in SnapCenter pour VMware vSphere, le plug-in est enregistré en tant qu'extension dans vCenter, tous les groupes de ressources sont en mode production et toutes les planifications sont activées.

.Étapes
. Facultatif : sauvegardez le référentiel MySQL du plug-in SnapCenter pour VMware vSphere si vous souhaitez le restaurer sur une nouvelle appliance virtuelle.
+
link:scpivs44_back_up_the_snapcenter_plug-in_for_vmware_vsphere_mysql_database.html["Sauvegardez le plug-in SnapCenter pour la base de données MySQL VMware vSphere"].

. Connectez-vous à l'interface graphique de gestion du plug-in SnapCenter pour VMware vSphere au format `\https://<OVA-IP-address>:8080`. Connectez-vous avec le nom d'utilisateur et le mot de passe administrateur définis au moment du déploiement, ainsi que le jeton MFA généré à l'aide de la console de maintenance.
+
L'adresse IP du plug-in SnapCenter pour VMware vSphere s'affiche lorsque vous déployez le plug-in.

. Cliquez sur *Configuration* dans le volet de navigation de gauche, puis désélectionnez l'option Service dans la section *Détails du plug-in* pour désactiver le plug-in.
. Confirmez votre choix.
+
** Si vous n'avez utilisé que le plug-in SnapCenter pour VMware vSphere pour effectuer des sauvegardes cohérentes avec les machines virtuelles
+
Le plug-in est désactivé et aucune autre action n'est requise.

** Si vous avez utilisé le plug-in SnapCenter pour VMware vSphere pour effectuer des sauvegardes cohérentes avec les applications
+
Le plug-in est désactivé et un nettoyage supplémentaire est requis.

+
... Connectez-vous à VMware vSphere.
... Mettre la machine virtuelle hors tension.
... Dans l'écran de navigation de gauche, cliquez avec le bouton droit de la souris sur l'instance du plug-in SnapCenter pour VMware vSphere (le nom du `.ova` fichier utilisé lors du déploiement de l'appliance virtuelle) et sélectionnez *Supprimer du disque*.
... Connectez-vous à SnapCenter et supprimez l'hôte vSphere.





