---
sidebar: sidebar 
permalink: scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere_01.html 
keywords:  
summary:  
---
= Déployez le plug-in SnapCenter pour VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Pour utiliser les fonctionnalités de SnapCenter pour protéger les machines virtuelles, les datastores et les bases de données cohérentes au niveau des applications sur les machines virtualisées, vous devez déployer le plug-in SnapCenter pour VMware vSphere.
Le link:scpivs44_download_the_ova_open_virtual_appliance.html["Télécharger Open Virtual Appliance (OVA)"^] Fournit des instructions pour télécharger les fichiers OVA.

. Pour VMware vCenter 7.0.3 et versions ultérieures, suivez les étapes décrites dans link:scpivs44_download_the_ova_open_virtual_appliance.html["Télécharger Open Virtual Appliance (OVA)"^] Pour importer les certificats dans vCenter.
. Dans votre navigateur, accédez à VMware vSphere vCenter.
+

NOTE: Pour les clients web HTML IPv6, vous devez utiliser Chrome ou Firefox.

. Connectez-vous à la page d'ouverture de session unique *VMware vCenter*.
. Dans le volet navigation, cliquez avec le bouton droit de la souris sur un objet d'inventaire qui est un objet parent valide d'une machine virtuelle, tel qu'un datacenter, un dossier, un cluster ou un hôte, puis sélectionnez *déployer modèle OVF* pour démarrer l'assistant de déploiement VMware.
. Sur la page *Sélectionner un modèle OVF*, indiquez l'emplacement du `.ova` (Comme indiqué dans le tableau suivant) et cliquez sur *Suivant*.
+
|===
| Sur cette page de l'assistant… | Faites cela… 


| Sélectionnez un nom et un dossier | Entrez un nom unique pour la machine virtuelle ou la vApp et sélectionnez un emplacement de déploiement. 


| Sélectionnez une ressource | Sélectionnez une ressource dans laquelle vous souhaitez exécuter le modèle de machine virtuelle déployé. 


| Vérifiez les détails | Vérifiez le `.ova` détails du modèle. 


| Contrats de licence | Cochez la case *J'accepte tous les accords de licence*. 


| Sélectionnez stockage | Définir où et comment stocker les fichiers pour le modèle OVF déployé. 


| Sélectionnez réseaux | Sélectionnez un réseau source et mappez-le sur un réseau de destination. 


| Personnaliser le modèle  a| 
Dans *s'inscrire à vCenter* existant, saisissez les informations d'identification vCenter. Dans *Créer un plug-in SnapCenter pour les informations d'identification VMware vSphere*, entrez les informations d'identification du plug-in SnapCenter pour VMware vSphere.


NOTE: Notez le nom d'utilisateur et le mot de passe que vous spécifiez. Vous devez utiliser ces informations d'identification pour modifier ultérieurement la configuration du plug-in SnapCenter pour VMware vSphere.

Dans la section *Configuration des propriétés réseau*, entrez les informations réseau. Dans la section *Date et heure de configuration*, sélectionnez le fuseau horaire où se trouve le vCenter.



| Prêt à terminer | Vérifiez la page et cliquez sur *Terminer*. 
|===
+

NOTE: Tous les hôtes doivent être configurés avec des adresses IP (les noms d'hôte FQDN ne sont pas pris en charge). L'opération de déploiement ne permet pas de valider vos informations avant le déploiement.

. Accédez à la machine virtuelle sur laquelle le plug-in SnapCenter pour VMware vSphere a été déployé, puis cliquez sur l'onglet *Résumé*, puis cliquez sur la case *mise sous tension* pour démarrer le plug-in SnapCenter pour VMware vSphere.
. Pendant que le plug-in SnapCenter pour VMware vSphere est sous tension, cliquez avec le bouton droit de la souris sur le plug-in SnapCenter déployé pour VMware vSphere, sélectionnez *OS invité*, puis cliquez sur *installer les outils VMware*.
+
Le déploiement peut prendre quelques minutes. Un déploiement réussi est indiqué lorsque le plug-in SnapCenter pour VMware vSphere est sous tension, que les outils VMware sont installés et que l'écran vous invite à vous connecter au plug-in SnapCenter pour VMware vSphere.

+
L'écran affiche l'adresse IP à laquelle le plug-in SnapCenter pour VMware vSphere est déployé. Notez l'adresse IP. Vous devez vous connecter à l'interface graphique de gestion du plug-in SnapCenter pour VMware vSphere si vous souhaitez modifier la configuration du plug-in SnapCenter pour VMware vSphere.

. Connectez-vous à l'interface graphique de gestion du plug-in SnapCenter pour VMware vSphere à l'aide de l'adresse IP affichée sur l'écran de déploiement à l'aide des informations d'identification fournies dans l'assistant de déploiement, puis vérifiez sur le tableau de bord que le plug-in SnapCenter pour VMware vSphere est connecté à vCenter et activé.
+
Utiliser le format `\https://<appliance-IP-address>:8080` Pour accéder à l'interface graphique de gestion.

+
Connectez-vous avec le nom d'utilisateur et le mot de passe administrateur définis au moment du déploiement, ainsi que le jeton MFA généré à l'aide de la console de maintenance.

. Connectez-vous au client HTML5 vCenter, puis cliquez sur *Menu* dans la barre d'outils, puis sélectionnez *Plug-in SnapCenter pour VMware vSphere*

