---
sidebar: sidebar 
permalink: scpivs44_restore_vmdks_from_backups.html 
keywords:  
summary: 'Il est possible de restaurer des VMDK existants, ou des VMDK supprimés ou détachés, à partir d"une sauvegarde primaire ou secondaire de machines virtuelles traditionnelles ou vvol.' 
---
= Restaurer des VMDK à partir des sauvegardes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il est possible de restaurer des VMDK existants, ou des VMDK supprimés ou détachés, à partir d'une sauvegarde primaire ou secondaire de machines virtuelles traditionnelles ou vvol.

Vous pouvez restaurer un ou plusieurs disques virtuels (VMDK) sur une machine virtuelle vers le même datastore.


TIP: Pour améliorer les performances des opérations de restauration dans les environnements NFS, activez l'API VMware vStorage pour l'intégration de baies (VAAI).

.Avant de commencer
* Une sauvegarde doit exister.
+
Vous devez avoir créé une sauvegarde de la machine virtuelle à l'aide du plug-in SnapCenter pour VMware vSphere.

* La machine virtuelle ne doit pas être en transit.
+
La machine virtuelle à restaurer ne doit pas être dans un état vMotion ou Storage vMotion.



.Description de la tâche
* Si le VMDK est supprimé ou détaché de la machine virtuelle, l'opération de restauration le lie à la machine virtuelle.
* Une opération de restauration peut échouer si le niveau de stockage de la FabricPool où se trouve la machine virtuelle est indisponible.
* Les opérations de liaison et de restauration connectent les VMDK à l'aide du contrôleur SCSI par défaut. Cependant, lorsque des VMDK reliés à une machine virtuelle avec un disque NVMe sont sauvegardés, les opérations de connexion et de restauration utilisent le contrôleur NVMe si disponible.


.Étapes
. Dans l’interface utilisateur du client VMware vSphere, sélectionnez *Menu* dans la barre d’outils, puis sélectionnez *VM et modèles* dans la liste déroulante.
. Dans le volet gauche du navigateur, cliquez avec le bouton droit de la souris sur une machine virtuelle, puis sélectionnez *SnapCenter Plug-in pour VMware vSphere* dans la liste déroulante, puis sélectionnez *Restore* dans la liste déroulante secondaire.
. Dans l'assistant *Restaurer*, sur la page Sélectionner une sauvegarde, sélectionnez la copie de sauvegarde à partir de laquelle vous souhaitez effectuer la restauration.
+
Vous pouvez rechercher un nom de sauvegarde spécifique ou un nom de sauvegarde partielle, ou bien filtrer la liste des sauvegardes en sélectionnant l'icône de filtre et en sélectionnant une plage de date et d'heure, en indiquant si vous voulez des sauvegardes contenant des snapshots VMware, si vous voulez des sauvegardes montées et un emplacement principal ou secondaire. Sélectionnez *OK* pour revenir à l'assistant.

. Sur la page *Sélectionner l'étendue*, sélectionnez la destination de restauration.
+
|===
| Pour restaurer... | Spécifiez la destination de restauration… 


| Le datastore d'origine | Sélectionnez *disque particulier* dans la liste déroulante, puis sélectionnez *Suivant*. Dans la table de sélection du datastore, vous pouvez sélectionner ou désélectionner tout VMDK. 


| Un autre datastore dans un autre emplacement | Sélectionnez le datastore de destination et sélectionnez un autre datastore dans la liste. 
|===
. Sur la page *Sélectionner un emplacement*, sélectionnez l'instantané à restaurer (principal ou secondaire).
. Consultez la page Résumé, puis sélectionnez *Terminer*.
. Facultatif : surveillez la progression de l'opération en sélectionnant *tâches récentes* au bas de l'écran.
. Actualiser l'écran pour afficher les informations mises à jour.

