---
sidebar: sidebar 
permalink: scpivs44_manage_resource_groups.html 
keywords:  
summary: Vous pouvez créer, modifier et supprimer des groupes de ressources de sauvegarde et effectuer des opérations de sauvegarde sur des groupes de ressources. 
---
= Gérer les groupes de ressources
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez créer, modifier et supprimer des groupes de ressources de sauvegarde et effectuer des opérations de sauvegarde sur des groupes de ressources.


NOTE: Ces groupes de ressources sont appelés tâches de sauvegarde dans Virtual Storage Console (VSC).



== Suspendre et reprendre les opérations sur les groupes de ressources

Suspendre les opérations planifiées sur un groupe de ressources.  Réactivez-les lorsque cela est nécessaire.

.Étapes
. Dans le volet de navigation de gauche du plug-in SCV, sélectionnez *groupes de ressources*, sélectionnez un groupe de ressources et sélectionnez *suspendre* (ou sélectionnez *reprendre*).
. Dans la boîte de confirmation, sélectionnez *OK* pour confirmer.


.Une fois que vous avez terminé
Sur la page groupes de ressources, l'état du travail de la ressource suspendue est `Under_Maintenance`. Vous devrez peut-être faire défiler la liste vers la droite pour afficher la colonne Statut du travail.

Après la reprise des opérations de sauvegarde, l'état du travail devient `Production`.



== Modifier les groupes de ressources

Vous pouvez supprimer ou ajouter des ressources dans des groupes de ressources dans vCenter, détacher ou attacher des stratégies, modifier des plannings ou modifier toute autre option de groupe de ressources.

.Description de la tâche
Si vous souhaitez modifier le nom d'un groupe de ressources, n'utilisez pas les caractères spéciaux suivants dans les noms de VM, datastore, stratégie, sauvegarde ou groupe de ressources :

% Et * $ # @ ! \ / : * ? " < > - | ; ' , et l'espace. Un caractère de soulignement (_) est autorisé.

.Étapes
. Dans le volet de navigation de gauche du plug-in SCV, sélectionnez *groupes de ressources*, puis sélectionnez un groupe de ressources et sélectionnez *Modifier*.
. Dans la liste de gauche de l'assistant *Modifier le groupe de ressources*, sélectionnez la catégorie que vous souhaitez modifier et entrez vos modifications.
+
Vous pouvez modifier plusieurs catégories. Vous pouvez également modifier des ressources protégées secondaires dans cette option.

. Sélectionnez *Suivant* jusqu'à ce que la page Résumé s'affiche, puis sélectionnez *Terminer*.




== Supprimer des groupes de ressources

Supprimez un groupe de ressources dans vCenter si vous n’avez pas besoin de protéger les ressources.  Supprimez tous les groupes de ressources avant de supprimer SnapCenter Plug-in for VMware vSphere.

.Description de la tâche
Toutes les opérations de suppression de groupe de ressources sont effectuées sous forme de suppressions forcées.  Lorsque vous supprimez un groupe de ressources, le système détache toutes les stratégies du groupe de ressources vCenter, supprime le groupe de ressources de SnapCenter Plug-in for VMware vSphere et supprime toutes les sauvegardes et tous les snapshots du groupe de ressources.


NOTE: Dans une relation SnapVault , vous ne pouvez pas supprimer le dernier instantané, par conséquent vous ne pouvez pas supprimer le groupe de ressources.  Avant de supprimer un groupe de ressources dans une relation SnapVault , utilisez System Manager ou ONTAP CLI pour supprimer la relation, puis supprimez le dernier snapshot.

.Étapes
. Dans le volet de navigation de gauche du plug-in SCV, sélectionnez *groupes de ressources*, puis sélectionnez un groupe de ressources et sélectionnez *Supprimer*.
. Dans la boîte de dialogue de confirmation *Supprimer le groupe de ressources*, sélectionnez *OK* pour confirmer.  La suppression d’un groupe de ressources ne supprime pas la protection secondaire.  Si nécessaire, utilisez le Gestionnaire système pour supprimer la protection secondaire.  Les groupes de cohérence créés pour le groupe de ressources ne sont pas automatiquement supprimés ; vous devez les supprimer manuellement d' ONTAP à l'aide de System Manager ou d'une autre interface prise en charge.

