---
sidebar: sidebar 
permalink: scpivs44_manage_the_vmware_vsphere_web_client_service.html 
keywords:  
summary: Si le client SnapCenter VMware vSphere ne se comporte pas correctement, vous devrez peut-être effacer le cache du navigateur. Si le problème persiste, redémarrez le service client VMware vSphere. 
---
= Redémarrez le service client VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si le client SnapCenter VMware vSphere ne se comporte pas correctement, vous devrez peut-être effacer le cache du navigateur. Si le problème persiste, redémarrez le service client VMware vSphere.



== Redémarrez le service client Web dans un vCenter Linux

Si votre vCenter se trouve sur une appliance Linux, vous devez utiliser les commandes Linux pour redémarrer le service client SnapCenter VMware vSphere.

.Avant de commencer
Vous devez exécuter vCenter 6.5 ou une version ultérieure.

.Étapes
. Utilisez SSH pour vous connecter à l'appliance vCenter Server en tant que root.
. Accédez au shell de l'appliance ou AU shell BASH à l'aide de la commande suivante :
+
`shell`

. Arrêtez le service client Web à l'aide de la commande HTML5 suivante :
+
`service-control --stop vsphere-ui`

. Supprimez tous les packages scvm obsolètes sur vCenter à l'aide de la commande HTML5 suivante :
+
`etc/vmware/vsphere-ui/vc-packages/vsphere-client-serenity/rm -rf com.netapp.scv.client-<version_number>`

+

IMPORTANT: Ne supprimez pas les packages VASA ou vCenter 7.x et versions ultérieures.

. Démarrez le service client Web à l'aide de la commande HTML5 suivante :
+
`service-control --start vsphere-ui`


