---
sidebar: sidebar 
permalink: scpivs44_add_a_single_vm_or_datastore_to_a_resource_group.html 
keywords:  
summary: 'Vous pouvez ajouter rapidement une machine virtuelle ou un datastore unique à n"importe quel groupe de ressources existant géré par le plug-in SnapCenter pour VMware vSphere.' 
---
= Ajoutez un seul serveur virtuel ou datastore à un groupe de ressources
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez ajouter rapidement une machine virtuelle ou un datastore unique à n'importe quel groupe de ressources existant géré par le plug-in SnapCenter pour VMware vSphere.

.Description de la tâche
Vous pouvez ajouter des datastores SAN et NAS, mais pas des datastores VSAN ou VVOL.

.Étapes
. Dans l’interface utilisateur du client vSphere, sélectionnez *Menu* dans la barre d’outils et accédez à la machine virtuelle ou à la banque de données que vous souhaitez ajouter.
. Dans le volet gauche du navigateur, cliquez avec le bouton droit de la souris sur la machine virtuelle ou le datastore, sélectionnez *SnapCenter Plug-in pour VMware vSphere* > *Ajouter au groupe de ressources* dans la liste déroulante secondaire.
+
Le système vérifie d'abord que SnapCenter gère et est compatible avec le système de stockage sur lequel se trouve la machine virtuelle sélectionnée, puis affiche la page *Ajouter au groupe de ressources*. Si le message s'affiche `SnapCenter Compatibility Error` S'affiche, la VM sélectionnée n'est pas compatible avec SnapCenter et vous devez d'abord ajouter la VM de stockage appropriée à SnapCenter.

. Dans la page *Ajouter au groupe de ressources*, sélectionnez un groupe de ressources, puis cliquez sur *OK*.
+
Lorsque vous sélectionnez *OK*, le système vérifie d'abord que SnapCenter gère et est compatible avec le stockage sur lequel se trouvent les machines virtuelles ou datastores sélectionnés.

+
Si le message `Selected <resource-name> is not SnapCenter compatible` s'affiche, la machine virtuelle ou le datastore sélectionné n'est pas compatible avec SnapCenter. Pour plus d'informations, reportez-vous à la section link:scpivs44_create_resource_groups_for_vms_and_datastores.html#manage-compatibility-check-failures["Gérer les échecs de contrôle de compatibilité"] .


