---
sidebar: sidebar 
permalink: scpivs44_information_not_displayed_after_upgrading_to_a_new_patch_of_the_same_release.html 
keywords:  
summary: 'Après la mise à niveau du plug-in SnapCenter pour VMware vSphere vers un nouveau correctif de la même version, il est possible que les tâches récentes ou d"autres informations ne s"affichent pas dans le tableau de bord et le moniteur des tâches.' 
---
= Informations non affichées après la mise à niveau vers un nouveau correctif de la même version
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Après la mise à niveau du plug-in SnapCenter pour VMware vSphere vers un nouveau correctif de la même version, il est possible que les tâches récentes ou d'autres informations ne s'affichent pas dans le tableau de bord et le moniteur des tâches.

Si vous effectuez une mise à niveau vers un nouveau correctif de la même version, vous devez effacer le cache SnapCenter Plug-in pour VMware vSphere sur le serveur Web vCenter et redémarrer le serveur avant la mise à niveau ou l'enregistrement.

Si le cache du plug-in n'est pas effacé, les travaux récents ne sont pas affichés dans le tableau de bord et le moniteur de tâches dans les scénarios suivants :

* Le plug-in SnapCenter pour VMware vSphere a été déployé à l'aide de vCenter, puis mis à niveau ultérieurement vers un correctif dans la même version.
* L'appliance virtuelle SnapCenter VMware a été déployée dans vCenter 1. Par la suite, ce plug-in SnapCenter pour VMware vSphere a été enregistré dans un nouveau vCenter2. Une nouvelle instance du plug-in SnapCenter pour VMware vSphere est créée avec un correctif et enregistrée dans vCenter1. Toutefois, comme vCenter1 dispose toujours du plug-in en cache du premier plug-in SnapCenter pour VMware vSphere sans le correctif, le cache doit être effacé.


Le cache se trouve dans les emplacements suivants, en fonction du type de système d'exploitation du serveur :

* Appliance vCenter Server Linux
+
`/etc/vmware/vsphere-client/vc-packages/vsphere-client-serenity/`

* Windows
+
`%PROGRAMFILES%/VMware/vSphere client/vc-packages/vsphere-client-serenity/`





== Solution de contournement si vous avez déjà mis à niveau avant de supprimer le cache

. Connectez-vous à l'interface utilisateur de gestion du SnapCenter Plug-in for VMware vSphere .
+
L'adresse IP s'affiche lorsque vous déployez le plug-in SnapCenter pour VMware vSphere.

. Sélectionnez *Configuration* dans le volet de navigation de gauche, puis sélectionnez l'option Service dans la section *Détails du plug-in* pour désactiver le plug-in.
+
Le plug-in SnapCenter pour le service VMware vSphere est désactivé et l'extension n'est pas enregistrée dans vCenter.

. Localisez le `vsphere-client-serenity` puis localisez le `com.netapp.scv.client-<release-number>` et supprimez-le.
+
Le nom du dossier change pour chaque version.

. Redémarrez vCenter Server.
. Connectez-vous au client VMware vSphere.
. Sélectionnez *Configuration* dans le volet de navigation de gauche, puis sélectionnez l'option Service dans la section *Détails du plug-in* pour activer le plug-in.
+
Le plug-in SnapCenter pour le service VMware vSphere est activé et l'extension est enregistrée dans vCenter.


