---
sidebar: sidebar 
permalink: scpivs44_minimum_ontap_privileges_required.html 
keywords:  
summary: Les privilèges minimum ONTAP requis varient en fonction des plug-ins SnapCenter utilisés pour la protection des données. 
---
= Privilèges ONTAP requis
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les privilèges minimum ONTAP requis varient en fonction des plug-ins SnapCenter utilisés pour la protection des données.


NOTE: À partir du plug-in SnapCenter pour VMware (SCV) 5.0, vous devez ajouter des applications de type HTTP et ONTAPI comme méthodes de connexion utilisateur pour tous les utilisateurs ONTAP disposant d'un accès personnalisé basé sur les rôles au SCV. Sans accès à ces applications, les sauvegardes échoueront. Vous devez redémarrer le service SCV pour reconnaître les modifications apportées aux méthodes de connexion utilisateur ONTAP.



== Privilèges minimum ONTAP requis

Tous les plug-ins SnapCenter requièrent les privilèges minimaux suivants :

|===


| Commandes All-Access : privilèges minimum requis pour ONTAP 8.3 et versions ultérieures. 


| event generate-autosupport-log 


| l'historique des tâches s'affiche
affichage du travail
fin de la tâche 


| lun create lun delete lun igroup add lun igroup create lun igroup delete lun igroup rename lun igroup show lun mapping add-reporting-nodes lun mapping create lun mapping create lun mapping delete lun mapping delete-reporting-nodes lun mapping show lun modify lun move-in-volume lun offline lun lun en ligne lun persistent-reservation clear lun resize série affichage de la lun 


| snapmirror liste-destinations snapmirror add-règle snapmirror règle modification-règle snapmirror règle suppression-règle snapmirror règle snapmirror show snapmirror restore snapmirror show-show-history snapmirror mise à jour de snapmirror snapmirror update-ls-set 


| Version 


| création de clones de volumes
clone de volume affiche
démarrage du fractionnement du clone de volume
arrêt du fractionnement du clone de volume
création de volumes
suppression d'un volume
destruction des volumes
création d'un clone de fichiers de volumes
volume fichier show-disk-usage
volume hors ligne
volume en ligne
modification de volume
création de qtree volume
suppression qtree du volume
modification de qtree volume
volume qtree show
restrictions de volume
volume affiché
création de copies snapshot de volume
suppression du snapshot de volume
modification de snapshot de volume
renommage snapshot de volume
restauration snapshot du volume
fichier de restauration de snapshot de volume
snapshot de volume apparaît
démontage de volume 


| vserver cifs vserver cifs share cifs share create vserver cifs share delete vserver cifs shadowcopy show vserver cifs share show vserver cifs show vserver cifs vserver export-policy vserver export-policy create vserver export-policy delete vserver export-policy rule create vserver export-policy rule show vserver export-policy show vserver iscsi connection show vserver iscsi subsystem controller vserver nvme subsystem controller show vserver nvme subsystem map vserver nvme subsystem map show vserver nvme subsystem map add vserver nvme subsystem map remove vserver subsystem nvme subsystem host show vserver nvme subsystem host show vserver nvme subsystem host add nvme subsystem host delete vserver subsystem nvme namespace affiche les failover-groups de l'interface réseau de l'interface réseau 
|===
|===
| Commandes en lecture seule : privilèges minimum requis pour ONTAP 8.3 et versions ultérieures 


| l'identité du cluster show network interface show vserver peer vserver show 
|===
Vous pouvez ignorer la commande _cluster Identity show_ cluster level lors de la création d'un rôle à associer au vServer de données.


NOTE: Vous pouvez ignorer les messages d'avertissement concernant les commandes vServer non prises en charge.



== Autres informations sur ONTAP

* Si vous exécutez ONTAP 8.2.x :
+
Vous devez vous connecter en tant que `vsadmin` Sur la machine virtuelle de stockage pour disposer des privilèges appropriés pour les opérations du plug-in SnapCenter pour VMware vSphere.

* Si vous exécutez ONTAP 8.3 et versions ultérieures :
+
Vous devez vous connecter en tant que `vsadmin` ou avec un rôle dont les privilèges sont minimum indiqués dans les tableaux ci-dessus.

* Vous devez être l'administrateur du cluster pour créer et gérer les rôles utilisateur. Vous pouvez associer les utilisateurs à la machine virtuelle de stockage du cluster ou à la machine virtuelle de stockage.
* Vous avez besoin de ONTAP 9.12.1 ou de versions ultérieures pour utiliser la fonctionnalité de synchronisation active de SnapMirror.
* Pour utiliser la fonction d'instantané inviolable (TPS) :
+
** ONTAP 9.13.1 et versions ultérieures sont nécessaires pour SAN
** ONTAP 9.12.1 et versions ultérieures sont nécessaires pour NFS


* Pour NVMe over TCP et le protocole NVMe over FC, vous avez besoin de ONTAP 9.10.1 et versions ultérieures.



NOTE: Depuis la version 9.11.1 de ONTAP, la communication avec le cluster ONTAP s'effectue via des API REST. L'application http doit être activée pour l'utilisateur ONTAP. Cependant, si des problèmes sont détectés avec les API REST ONTAP, la clé de configuration 'FORCE_ZAPI' facilite le basculement vers le workflow ZAPI traditionnel. Vous devrez peut-être ajouter ou mettre à jour cette clé à l'aide des API DE configuration et la définir sur vrai. Pour plus d'informations, reportez-vous à l'article de la base de connaissances https://kb.netapp.com/mgmt/SnapCenter/How_to_use_RestAPI_to_edit_configuration_parameters_in_SCV["Comment utiliser RestAPI pour modifier les paramètres de configuration dans SCV"] .
