---
sidebar: sidebar 
permalink: scpivs44_rest_apis_fail_stuck_jobs.html 
keywords:  
summary: 'Pour rechercher les identifiants de travail des travaux des clients VMware vSphere à l"aide du plug-in SnapCenter pour les API REST VMware vSphere, vous devez utiliser les appels de l"API REST pour VMware vSphere.' 
---
= L'API REST pour marquer les travaux bloqués comme ayant échoué
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Pour rechercher les identifiants de travail des travaux des clients VMware vSphere à l'aide du plug-in SnapCenter pour les API REST VMware vSphere, vous devez utiliser les appels de l'API REST pour VMware vSphere. Ces API REST ont été ajoutées au plug-in SnapCenter pour VMware vSphere 4.4.

Pour chaque API REST, ajoutez \https://<server>:<port>` au début de l'API REST pour former un noeud final complet.

Utilisez l'API REST suivante de la section travaux pour modifier les travaux bloqués à l'état en cours d'exécution en tant qu'échec :

|===
| API REST | Commentaires 


| `/4.1/jobs/{id}/failJobs` | Lorsque vous transmettez les identifiants des tâches bloquées dans un état d'exécution, `failJobs` marque ces tâches comme ayant échoué.  Pour identifier les tâches bloquées dans un état d'exécution, utilisez l'interface utilisateur du moniteur de tâches pour voir l'état de chaque tâche et l'ID de tâche. 
|===