---
sidebar: sidebar 
permalink: scpivs44_migration_overview.html 
keywords:  
summary:  
---
= Présentation de la migration
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La commande de migration migre les métadonnées de #SnapCenter 4.0 et versions ultérieures uniquement#. Si vous utilisez une version antérieure de SnapCenter, vous devez d'abord effectuer la mise à niveau avant de pouvoir effectuer la migration.

* Inclus dans la migration
+
** Qu'est-ce qui est migré
+
Les métadonnées SnapCenter, qui comprennent les systèmes de stockage, les accélérateurs personnalisés et les paramètres d'e-mail dans SnapCenter le fichier de configuration, les règles, les groupes de ressources, les métadonnées de sauvegarde et les montages. (la migration échoue lorsqu'elle rencontre des prescripteurs ou des postscripts)

** Ce qui n'est pas migré
+
Scripts prédéfinis et post configurés pour les groupes de ressources

+
Sessions de restauration de fichiers invités actives, identifiants de restauration de fichiers invités et machines virtuelles proxy

+
Si vous commencez la migration lorsqu'une session de restauration de fichier invité est active, la session est supprimée et le disque joint n'est pas démonté. Vous devrez peut-être supprimer le disque connecté manuellement.

+
`scbr.override` fichier de configuration



* Les hôtes SnapCenter sont suspendus
+
Pour garantir la réussite de la migration, la commande de migration suspend tous les hôtes enregistrés avec SnapCenter. Une fois le processus de migration terminé, les hôtes SnapCenter reprennent.

* Processus de l'applet de commande de migration
+
Vous devez utiliser la cmdlet Windows PowerShell `invoke-SCVOVAMigration` Pour chaque instance du plug-in SnapCenter VMware enregistré auprès de SnapCenter.

+
L'applet de commande effectue les opérations suivantes :

+
** Suspend tous les planifications pour éviter les échecs de travail pendant la migration. Une fois la migration réussie, les planifications sont automatiquement réactivées.
** Migration des connexions de stockage et des métadonnées.
** Crée des planifications de sauvegarde pour les sauvegardes post-migration.
** Désinstalle le plug-in SnapCenter existant pour VMware vSphere à partir de l'hôte Windows.
+
Si le plug-in SnapCenter VMware est installé sur l'hôte SnapCenter Server et que la protection est configurée pour le référentiel SnapCenter, le processus de migration désinstalle également le package du plug-in Windows contenant le plug-in SnapCenter pour VMware vSphere et le plug-in SnapCenter pour Windows, Puis réinstalle la dernière version du plug-in SnapCenter pour Windows afin de prendre en charge la protection du référentiel. Le type d'hôte dans l'interface utilisateur graphique SnapCenter passe de vSphere à Windows.

** Supprime l'hôte vSphere et les groupes de ressources du serveur SnapCenter Windows.
** Active les tâches de sauvegarde sur le plug-in VMware SnapCenter basé sur Linux.
** Enregistre l'hôte vSphere pour le plug-in SnapCenter VMware `avec SnapCenter pour prendre en charge les sauvegardes basées sur les applications de bases de données virtualisées et de systèmes de fichiers (application sur sauvegardes VMDK).


* L'emplacement de stockage des métadonnées
+
Les métadonnées pour les sauvegardes VMDK basées sur les applications sont stockées dans le référentiel SnapCenter Server. Les métadonnées pour la sauvegarde des machines virtuelles et des datastores sont stockées dans le référentiel MySQL du plug-in SnapCenter VMware.


