---
sidebar: sidebar 
permalink: scpivs44_how_to_configure_ontap_rbac_for_snapcenter_plug-in_for_vmware_vsphere.html 
keywords:  
summary: 'Le contrôle d"accès basé sur des rôles (RBAC) ONTAP s"applique uniquement aux tâches du serveur SnapCenter cohérentes au niveau des applications (application sur VMDK).' 
---
= Comment configurer le RBAC ONTAP pour le plug-in SnapCenter pour VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le contrôle d'accès basé sur des rôles (RBAC) ONTAP s'applique uniquement aux tâches du serveur SnapCenter cohérentes au niveau des applications (application sur VMDK).


NOTE: À partir du plug-in SnapCenter pour VMware (SCV) 5.0, vous devez ajouter des applications de type HTTP et ONTAPI comme méthodes de connexion utilisateur pour tous les utilisateurs ONTAP disposant d'un accès personnalisé basé sur les rôles au SCV. Sans accès à ces applications, les sauvegardes échoueront. Vous devez redémarrer le service SCV pour reconnaître les modifications apportées aux méthodes de connexion utilisateur ONTAP. Pour plus d'informations sur la création ou la modification de comptes de connexion, reportez-vous à https://docs.netapp.com/us-en/ontap/authentication/config-worksheets-reference.html["Feuilles de calcul pour l'authentification de l'administrateur et la configuration du RBAC"]la section .

Vous devez configurer ONTAP RBAC sur le système de stockage si vous souhaitez l'utiliser avec le plug-in SnapCenter pour VMware vSphere. Depuis ONTAP, vous devez effectuer les tâches suivantes :

* Créez un rôle unique.
+
https://docs.netapp.com/us-en/ontap/concepts/administrator-authentication-rbac-concept.html["Authentification de l'administrateur et RBAC"]

* Créez un nom d'utilisateur et un mot de passe (identifiants du système de stockage) dans ONTAP pour le rôle.
+
Ces informations d'identification du système de stockage sont nécessaires pour vous permettre de configurer les systèmes de stockage pour le plug-in SnapCenter pour VMware vSphere. Pour ce faire, entrez les informations d'identification dans le plug-in. Chaque fois que vous vous connectez à un système de stockage à l'aide de ces informations d'identification, l'ensemble des fonctions SnapCenter que vous avez configurées dans ONTAP s'affiche lorsque vous avez créé les informations d'identification.



Vous pouvez utiliser l'administrateur ou la connexion racine pour accéder à toutes les tâches SnapCenter. Cependant, il est conseillé d'utiliser la fonctionnalité RBAC fournie par ONTAP pour créer un ou plusieurs comptes personnalisés avec des privilèges d'accès limités.

Pour plus d'informations, reportez-vous link:scpivs44_minimum_ontap_privileges_required.html["Privilèges minimum ONTAP requis"^]à .
