---
sidebar: sidebar 
permalink: scpivs44_rest_api_workflow__restore_vmdks.html 
keywords:  
summary: 'Pour effectuer des opérations de restauration pour les VMDK à l"aide du plug-in SnapCenter pour les API REST VMware vSphere, vous devez suivre la séquence prescrite d"appels d"API REST.' 
---
= Flux de production des API REST pour la restauration des VMDK
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Pour effectuer des opérations de restauration pour les VMDK à l'aide du plug-in SnapCenter pour les API REST VMware vSphere, vous devez suivre la séquence prescrite d'appels d'API REST.

Pour chaque API REST, ajoutez `https://<server>:<port>` Au niveau de l'API REST, pour former un terminal complet.

|===
| Étape | API REST | Commentaires 


| 1 | Accédez à `http://<vCenter-IP>/mob` | Recherchez le moref de la VM à partir de l'URL des objets gérés VMware. Notez le *moref* pour la machine virtuelle dans laquelle se trouve le VMDK. 


| 2 | `/4.1/vm/{moref}/backups` | `Get VM Backups` Obtient la liste des sauvegardes pour la machine virtuelle spécifiée. Passez le *moref* de l'étape 1. Notez la *backupId* de la sauvegarde que vous souhaitez restaurer. 


| 3 | `/4.1/vm/backups/{backupId}/
snapshotlocations` | `Get snapshot locations` Obtient l'emplacement de la copie Snapshot pour la sauvegarde spécifiée. Passez le *backupId* de l'étape 2. Notez les informations *snapshotLocationsList*. 


| 4 | `/4.1/vm/{moref}/backups/
vmdklocations` | `Get Vmdk Locations` Obtient la liste des VMDK pour la machine virtuelle spécifiée. Notez les informations *vmdkLocationsList*. 


| 5 | `/4.1/vm/{ moref}/backups/
{backupId}/
availabledatastores` | `Get Available Datastores` obtient la liste des datastores disponibles pour l'opération de restauration. Passez le *moref* de l'étape 1. Passez le *backupId* de l'étape 2. Notez les informations *DatastoreNameList*. 


| 6 | `/4.1/vm/{moref}/backups/
availableesxhosts` | `Get available ESX Hosts` obtient les informations de l'hôte sur lequel la sauvegarde est stockée. Passez le *moref* de l'étape 1. Notez les informations *disponibleEsxHostsList*. 


| 7 | `/4.1/vm/{moref}/backups/
{backupId}/restorevmdks`  a| 
`Restore a VMDK from a backup` Restaure le VMDK spécifié à partir de la sauvegarde spécifiée. Dans l'attribut *esxHost*, transmettez les informations de *disponibleEsxHostsList* à l'étape 6. Transmettez les informations des étapes 3 à 5 à l'attribut *vmdkRestorelocations* :

* Dans l'attribut restoreFromLocation, transmettez les informations de snapshotLocationsList à l'étape 3.
* Dans l'attribut vmdkToRestore, transmettez les informations de vmdkLocationsList à l'étape 4.
* Dans l'attribut restoreTodatastore, transmettez les informations de DatastoreNameList à l'étape 5.


|===