---
sidebar: sidebar 
permalink: scpivs44_add_storage_01.html 
keywords:  
summary: 'L"ajout de stockage permet au plug-in SnapCenter pour VMware vSphere de reconnaître et de gérer les opérations de sauvegarde et de restauration dans vCenter.' 
---
= Ajouter du stockage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Avant de sauvegarder ou de restaurer des machines virtuelles, vous devez ajouter des clusters de stockage ou des machines virtuelles de stockage. L'ajout de stockage permet au plug-in SnapCenter pour VMware vSphere de reconnaître et de gérer les opérations de sauvegarde et de restauration dans vCenter.

* Dans quelle interface utilisateur choisir
+
Utilisez le client VMware vSphere pour ajouter du stockage.

* Grandes LUN
+
Le plug-in SnapCenter pour VMware vSphere 4.5 et versions ultérieures prend en charge les datastores dans des LUN de grande taille, jusqu'à 128 To sur des agrégats ASA. Pour les LUN de grande taille, SnapCenter ne prend en charge que les LUN à provisionnement lourd pour éviter la latence.

* Volumes virtuels VMware (vvols)
+
Vous devez d'abord ajouter le système de stockage vVols aux outils ONTAP pour VMware vSphere, puis l'ajouter au plug-in SnapCenter pour VMware vSphere.

+
Pour plus d'informations, voir https://docs.netapp.com/vapp-98/index.jsp["Les outils ONTAP pour VMware vSphere"^]



.Avant de commencer
Le serveur ESXi, le plug-in SnapCenter VMware et chaque vCenter doivent être synchronisés en même temps. Si vous essayez d'ajouter du stockage mais que les paramètres d'heure de vos vCenters ne sont pas synchronisés, l'opération peut échouer avec une erreur de certificat Java.

.Description de la tâche
Le plug-in SnapCenter pour VMware réalise des opérations de sauvegarde et de restauration sur les machines virtuelles de stockage directement connectées et sur les machines virtuelles de stockage dans un cluster de stockage.


NOTE: Si vous utilisez le plug-in SnapCenter pour VMware pour prendre en charge les sauvegardes basées sur les applications sur des VMDK, vous devez utiliser l'interface graphique de SnapCenter pour entrer les détails de l'authentification du stockage et enregistrer les systèmes de stockage.

* Pour les vCenters en mode lié, vous devez ajouter séparément des systèmes de stockage à chaque vCenter.
* Si vous ajoutez un SVM, les noms des VM de stockage doivent résoudre en tant que LIF de gestion.
+
Si vous avez ajouté des entrées au fichier _etc\hosts_ pour les noms de machines virtuelles de stockage dans SnapCenter, vous devez vous assurer qu'elles peuvent également être résolues à partir de l'appliance virtuelle. Si ce n'est pas le cas, vous devez ajouter des entrées similaires au fichier _etc/hosts_ de l'appliance.

+
Si vous ajoutez un serveur virtuel de stockage portant un nom qui ne peut pas être résolu sur la LIF de gestion, les tâches de sauvegarde planifiées échouent, car le plug-in ne peut pas détecter les datastores ou les volumes de cette machine virtuelle de stockage. Le cas échéant, ajoutez la VM de stockage à SnapCenter et spécifiez la LIF de gestion ou ajoutez un cluster qui contient le VM de stockage et spécifiez la LIF de cluster management.

* Les informations d'authentification du stockage ne sont pas partagées entre plusieurs instances du plug-in SnapCenter VMware ou entre Windows SnapCenter Server et le plug-in SnapCenter sur vCenter.


.Étapes
. Dans le volet navigateur de gauche du client vSphere, cliquez sur *Storage Systems*.
. Sur la page systèmes de stockage, sélectionnez l'option *Ajouter*.
. Dans l'assistant *Add Storage System*, entrez les informations de base sur la machine virtuelle de stockage ou le cluster comme indiqué dans le tableau suivant :
+
|===
| Pour ce champ… | Faites cela… 


| Adieu les migrations de données onéreuses | Entrez l'adresse IP du FQDN ou de la LIF de gestion d'un cluster de stockage ou d'une VM de stockage.
Le plug-in SnapCenter VMware ne prend pas en charge plusieurs machines virtuelles de stockage portant le même nom sur des clusters différents. 


| Méthode d'authentification | Sélectionnez informations d'identification ou certificat. Deux types de certificats sont pris en charge : - https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_a_CA_signed_certificate_for_storage_system_authentication_with_SCV["CERTIFICAT signé CA"^]- https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_a_self-signed_certificate_for_storage_system_authentication_with_SCV["Certificat auto-signé"^] 


| Nom d'utilisateur | Ce champ est visible lorsque vous sélectionnez informations d'identification comme méthode d'authentification. Entrez le nom d'utilisateur ONTAP utilisé pour vous connecter à la machine virtuelle de stockage ou au cluster. 


| Mot de passe | Ce champ est visible lorsque vous sélectionnez informations d'identification comme méthode d'authentification. Entrez le mot de passe de connexion de la machine virtuelle de stockage ou du cluster. 


| Certificat | Ce champ est visible lorsque vous sélectionnez certificat comme méthode d'authentification. Recherchez le fichier de certificat. 


| Clé privée | Ce champ est visible lorsque vous sélectionnez certificat comme méthode d'authentification. Recherchez le fichier de clé privée. 


| Protocole | Sélectionnez le protocole de stockage. 


| Port | Port accepté par le système de stockage.
- 443 pour la connexion HTTPS
- 80 pour la connexion HTTP 


| Délai dépassé | Entrez le nombre de secondes d'attente du plug-in VMware SnapCenter avant de procéder à la temporisation de l'opération. La valeur par défaut est 60 secondes. 


| Adresse IP préférée | Si la machine virtuelle de stockage possède plusieurs adresses IP de gestion, cochez cette case et entrez l'adresse IP que vous souhaitez utiliser le plug-in SnapCenter VMware.
*Remarque :* n'utilisez pas de crochets ([]) lors de la saisie de l'adresse IP. 


| Système de gestion des événements (EMS) et paramètres AutoSupport | Pour envoyer des messages EMS au syslog du système de stockage ou pour que des messages AutoSupport soient envoyés au système de stockage à des fins de protection appliquée, de restauration terminée ou d'échec, cochez la case appropriée. Cochez la case *Envoyer la notification AutoSupport pour les opérations ayant échoué au système de stockage* et la case *Log SnapCenter Server events to syslog* pour activer les notifications AutoSupport. 


| Consigner les événements du serveur SnapCenter dans syslog | Cochez la case pour consigner les événements du plug-in SnapCenter VMware. 


| Envoyer la notification AutoSupport en cas d'échec de l'opération dans le système de stockage | Cochez la case si vous souhaitez que la notification AutoSupport pour les tâches de protection des données ayant échoué. Vous devez également activer AutoSupport sur la machine virtuelle de stockage et configurer les paramètres de messagerie AutoSupport. 
|===
. Cliquez sur *Ajouter*.
+
Si vous avez ajouté un cluster de stockage, toutes les machines virtuelles de stockage de ce cluster sont automatiquement ajoutées. Les machines virtuelles de stockage ajoutées automatiquement (parfois appelées machines virtuelles de stockage « implicites ») sont affichées sur la page de résumé du cluster avec un tiret (-) au lieu d'un nom d'utilisateur. Les noms d'utilisateur sont affichés uniquement pour les entités de stockage explicites.


