---
sidebar: sidebar 
permalink: scpivs44_unregister_plugin_from_vcenter.html 
keywords:  
summary: 'Si vous arrêtez le service SnapCenter Plug-in for VMware vSphere dans un vCenter en mode lié, les groupes de ressources ne sont pas disponibles dans tous les vCenters liés, même lorsque le service SnapCenter Plug-in for VMware vSphere est exécuté dans les autres vCenters liés. Vous devez annuler l"enregistrement manuel du plug-in SnapCenter pour les extensions VMware vSphere.' 
---
= Annuler l'enregistrement du plug-in SnapCenter pour VMware vSphere à partir de vCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si vous arrêtez le service SnapCenter Plug-in for VMware vSphere dans un vCenter en mode lié, les groupes de ressources ne sont pas disponibles dans tous les vCenters liés, même lorsque le service SnapCenter Plug-in for VMware vSphere est exécuté dans les autres vCenters liés.

Vous devez annuler l'enregistrement manuel du plug-in SnapCenter pour les extensions VMware vSphere.

.Étapes
. Sur le vCenter lié sur lequel le plug-in SnapCenter pour VMware vSphere est arrêté, accédez au gestionnaire MOB (Managed Object Reference).
. Dans l'option Propriétés, sélectionnez *content* dans la colonne valeur, puis, dans l'écran suivant, sélectionnez *ExtensionManager* dans la colonne valeur pour afficher la liste des extensions enregistrées.
. Annuler l'enregistrement des extensions `com.netapp.scv.client` et `com.netapp.aegis`.

