---
sidebar: sidebar 
permalink: scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere.html 
keywords:  
summary: Pour utiliser les fonctionnalités de SnapCenter pour protéger les machines virtuelles, les datastores et les bases de données cohérentes au niveau des applications sur les machines virtualisées, vous devez déployer le plug-in SnapCenter pour VMware vSphere. 
---
= Déployez le plug-in SnapCenter pour VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Pour utiliser les fonctionnalités de SnapCenter pour protéger les machines virtuelles, les datastores et les bases de données cohérentes au niveau des applications sur les machines virtualisées, vous devez déployer le plug-in SnapCenter pour VMware vSphere.

.Avant de commencer
Cette section répertorie toutes les actions nécessaires que vous devez effectuer avant de commencer le déploiement.


NOTE:  Le déploiement OVA est pris en charge dans VMware vCenter 7u1 et versions ultérieures.

* Vous devez avoir lu les conditions de déploiement.
* Vous devez exécuter une version prise en charge de vCenter Server.
* Vous devez avoir configuré et configuré votre environnement vCenter Server.
* Vous devez avoir configuré un hôte ESXi pour le plug-in SnapCenter pour VMware vSphere VM.
* Vous devez avoir téléchargé le fichier .tar du plug-in SnapCenter pour VMware vSphere.
* Vous devez disposer des informations d'authentification de connexion pour votre instance de vCenter Server.
* Vous devez disposer d'un certificat avec des fichiers de clé publique et privée valides. Pour plus d'informations, reportez-vous aux articles de https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_Certificate_Resolution_Guide["Gestion des certificats de stockage"] la section.
* Vous devez vous être déconnecté et avoir fermé toutes les sessions de navigateur du client vSphere, puis supprimé le cache du navigateur pour éviter tout problème de cache du navigateur lors du déploiement du plug-in SnapCenter pour VMware vSphere.
* Vous devez avoir activé transport Layer Security (TLS) dans vCenter. Voir la documentation VMware.
* Si vous prévoyez d'effectuer des sauvegardes dans des instances vCenter autres que celles dans lesquelles le plug-in SnapCenter pour VMware vSphere est déployé, le serveur ESXi, le plug-in SnapCenter pour VMware vSphere et chaque serveur vCenter doivent être synchronisés en même temps.
* Pour protéger les machines virtuelles sur les datastores vvol, vous devez d'abord déployer les outils ONTAP pour VMware vSphere. Pour obtenir les informations les plus récentes sur les versions prises en charge des outils ONTAP, reportez-vous à la section https://imt.netapp.com/matrix/imt.jsp?components=134348;&solution=1517&isHWU&src=IMT["Matrice d'interopérabilité NetApp"^]. Les outils ONTAP provisionne et configurent le stockage sur ONTAP et sur le client web VMware.


Déployez le plug-in SnapCenter pour VMware vSphere dans le même fuseau horaire que vCenter. Les plannings de sauvegarde sont exécutés dans le fuseau horaire dans lequel le plug-in SnapCenter pour VMware vSphere est déployé. VCenter rapporte les données dans le fuseau horaire dans lequel se trouve vCenter. Par conséquent, si le plug-in SnapCenter pour VMware vSphere et vCenter se trouve dans des fuseaux horaires différents, les données du plug-in SnapCenter pour VMware vSphere Dashboard peuvent ne pas être identiques aux données des rapports.

.Étapes
. Pour VMware vCenter 7.0.3 et versions ultérieures, suivez les étapes décrites dans link:scpivs44_download_the_ova_open_virtual_appliance.html["Télécharger Open Virtual Appliance (OVA)"^] Pour importer les certificats dans vCenter.
. Dans votre navigateur, accédez à VMware vSphere vCenter.
+

NOTE: Pour les clients Web HTML d'adresse IPv6, vous devez utiliser Chrome ou Firefox.

. Connectez-vous à la page *Single Sign-on de VMware vCenter*.
. Dans le volet navigateur, cliquez avec le bouton droit de la souris sur un objet d'inventaire qui est un objet parent valide d'une machine virtuelle, tel qu'un centre de données, un cluster ou un hôte, et sélectionnez *déployer le modèle OVF* pour lancer l'assistant de déploiement VMware.
. Extrayez le fichier .tar, qui contient le fichier .ova dans votre système local. Sur la page *Sélectionner un modèle OVF*, indiquez l'emplacement du `.ova` fichier dans le dossier .tar extrait.
. Sélectionnez *Suivant*.
. Sur la page *Sélectionner un nom et un dossier*, entrez un nom unique pour la machine virtuelle ou la vApp, sélectionnez un emplacement de déploiement, puis sélectionnez *Suivant*.
+
Cette étape indique où importer le `.tar` Fichier dans vCenter. Le nom par défaut de la machine virtuelle est identique au nom de la machine virtuelle sélectionnée `.ova` fichier. Si vous modifiez le nom par défaut, choisissez un nom unique dans chaque dossier de VM de vCenter Server.

+
L'emplacement de déploiement par défaut de la machine virtuelle est l'objet d'inventaire au démarrage de l'assistant.

. Sur la page *Sélectionner une ressource*, sélectionnez la ressource dans laquelle vous souhaitez exécuter le modèle de machine virtuelle déployée, puis sélectionnez *Suivant*.
. Sur la page *vérifier les détails*, vérifiez les `.tar` détails du modèle et sélectionnez *Suivant*.
. Sur la page *accords de licence*, cochez la case *J'accepte tous les accords de licence*.
. Sur la page *Sélectionner le stockage*, définissez l'emplacement et le mode de stockage des fichiers pour le modèle OVF déployé.
+
.. Sélectionnez le format de disque pour les VMDK.
.. Sélectionnez une stratégie de stockage VM.
+
Cette option n'est disponible que si les stratégies de stockage sont activées sur la ressource de destination.

.. Sélectionnez un datastore pour stocker le modèle OVA déployé.
+
Le fichier de configuration et les fichiers de disque virtuel sont stockés dans le datastore.

+
Sélectionnez un datastore suffisamment grand pour héberger la machine virtuelle ou la vApp et tous les fichiers de disques virtuels associés.



. Sur la page *Select Networks*, procédez comme suit :
+
.. Sélectionner un réseau source et le mapper vers un réseau de destination,
+
La colonne Source Network répertorie tous les réseaux définis dans le modèle OVA.

.. Dans la section *Paramètres d'allocation IP*, sélectionnez le protocole d'adresse IP requis, puis sélectionnez *Suivant*.
+
Le plug-in SnapCenter pour VMware vSphere prend en charge une seule interface réseau. Si vous avez besoin de plusieurs cartes réseau, vous devez le configurer manuellement. Reportez-vous à la https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_create_additional_network_adapters_in_NDB_and_SCV_4.3["Article de la base de connaissances : comment créer des cartes réseau supplémentaires"^].



. Sur la page *Personnaliser le modèle*, procédez comme suit :
+
.. Dans la section *s'inscrire à vCenter* existant, entrez le nom de vCenter et les informations d'identification vCenter de l'appliance virtuelle.
+
Dans le champ *Nom d'utilisateur vCenter*, entrez le nom d'utilisateur au format `domain\username`.

.. Dans la section *Créer des références de distributeur sélectif*, saisissez les informations d'identification locales.
+
Dans le champ *Nom d'utilisateur*, saisissez le nom d'utilisateur local ; n'incluez pas les détails du domaine.

+

IMPORTANT: Notez le nom d'utilisateur et le mot de passe que vous spécifiez. Vous devez utiliser ces informations d'identification si vous souhaitez modifier ultérieurement la configuration du plug-in SnapCenter pour VMware vSphere.

.. Saisissez les informations d'identification de l'utilisateur principal.
.. Dans la section *Setup Network Properties*, entrez le nom d'hôte.
+
... Dans la section *Configuration des propriétés réseau IPv4*, entrez les informations réseau telles que l'adresse IPv4, le masque de réseau IPv4, la passerelle IPv4, le DNS principal IPv4, le DNS secondaire IPv4, et domaines de recherche IPv4.
... Dans la section *configurer les propriétés du réseau IPv6*, entrez les informations relatives au réseau telles que l'adresse IPv6, le masque de réseau IPv6, la passerelle IPv6, le DNS principal IPv6, le DNS secondaire IPv6, et les domaines de recherche IPv6.
+
Sélectionnez les champs d'adresse IPv4 ou IPv6, ou les deux, le cas échéant. Si vous utilisez à la fois des adresses IPv4 et IPv6, vous devez spécifier le DNS principal pour un seul d'entre eux.

+

IMPORTANT: Vous pouvez ignorer ces étapes et laisser les entrées vides dans la section *Configuration des propriétés du réseau*, si vous souhaitez continuer avec DHCP comme configuration du réseau.



.. Dans *Configuration Date et heure*, sélectionnez le fuseau horaire dans lequel se trouve le vCenter.


. Sur la page *prêt à terminer*, passez en revue la page et sélectionnez *Terminer*.
+
Tous les hôtes doivent être configurés avec des adresses IP (les noms d'hôte FQDN ne sont pas pris en charge). L'opération de déploiement ne permet pas de valider vos informations avant le déploiement.

+
Vous pouvez afficher la progression du déploiement à partir de la fenêtre tâches récentes pendant que vous attendez la fin des tâches d'importation et de déploiement du OVF.

+
Une fois le déploiement du plug-in SnapCenter pour VMware vSphere réussi, il est déployé en tant que VM Linux, enregistré auprès de vCenter et un client VMware vSphere est installé.

. Accédez à la machine virtuelle sur laquelle le plug-in SnapCenter pour VMware vSphere a été déployé, puis sélectionnez l'onglet *Résumé*, puis cochez la case *mise sous tension* pour démarrer l'appliance virtuelle.
. Pendant que le plug-in SnapCenter pour VMware vSphere est sous tension, cliquez avec le bouton droit de la souris sur le plug-in SnapCenter déployé pour VMware vSphere, sélectionnez *OS invité*, puis sélectionnez *installer les outils VMware*.
+
Les outils VMware sont installés sur la machine virtuelle sur laquelle le plug-in SnapCenter pour VMware vSphere est déployé. Pour plus d'informations sur l'installation des outils VMware, reportez-vous à la documentation VMware.

+
Le déploiement peut prendre quelques minutes. Un déploiement réussi est indiqué lorsque le plug-in SnapCenter pour VMware vSphere est sous tension, que les outils VMware sont installés et que l'écran vous invite à vous connecter au plug-in SnapCenter pour VMware vSphere. Vous pouvez basculer votre configuration réseau de DHCP vers statique au cours du premier redémarrage. Toutefois, le passage de statique à DHCP n'est pas pris en charge.

+
L'écran affiche l'adresse IP à laquelle le plug-in SnapCenter pour VMware vSphere est déployé. Notez l'adresse IP. Vous devez vous connecter à l'interface graphique de gestion du plug-in SnapCenter pour VMware vSphere si vous souhaitez modifier la configuration du plug-in SnapCenter pour VMware vSphere.

. Connectez-vous à l'interface graphique de gestion du plug-in SnapCenter pour VMware vSphere à l'aide de l'adresse IP affichée sur l'écran de déploiement et des informations d'identification fournies dans l'assistant de déploiement. vérifiez ensuite sur le tableau de bord que le plug-in SnapCenter pour VMware vSphere est correctement connecté à vCenter et activé.
+
Utiliser le format `\https://<appliance-IP-address>:8080` Pour accéder à l'interface graphique de gestion.

+
Connectez-vous avec le nom d'utilisateur et le mot de passe administrateur définis au moment du déploiement, ainsi que le jeton MFA généré à l'aide de la console de maintenance.

+
Si le plug-in SnapCenter pour VMware vSphere n'est pas activé, reportez-vous à la section link:scpivs44_restart_the_vmware_vsphere_web_client_service.html["Redémarrez le service client VMware vSphere"].

+
Si le nom d'hôte est 'UnifiedVSC/SCV, redémarrez l'appliance. Si le redémarrage de l'appareil ne change pas le nom d'hôte par rapport au nom d'hôte spécifié, vous devez réinstaller l'appareil.



.Une fois que vous avez terminé
Vous devez remplir le formulaire requis link:scpivs44_post_deployment_required_operations_and_issues.html["opérations de post-déploiement"].
