---
sidebar: sidebar 
permalink: scv48_add_certificates_to_certificate_store.html 
keywords:  
summary: 'Ajoutez les certificats racine et intermédiaire de l"autorité de certification à VMware vCenter afin de pouvoir approuver le certificat et les artefacts qui lui sont signés.' 
---
= Ajoutez des certificats à la boutique de certificats VMware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Avant d'installer Open Virtual Appliance (OVA), ajoutez le certificat à vCenter. Le fichier .tar contient les certificats OVA et Entrust Root et Intermediate, les certificats se trouvent dans le dossier certificats. Le déploiement OVA est pris en charge dans VMware vCenter 7u1 et versions ultérieures.

Dans VMware vCenter 7.0.3 et versions ultérieures, le fichier OVA signé par le certificat Entrust n'est plus approuvé. Vous devez effectuer la procédure suivante pour résoudre le problème.

.Étapes
. Connectez-vous avec le client vSphere au serveur vCenter.
. Accédez à *Administration > certificats > gestion des certificats*.
. En regard de *Trusted Root Store*, cliquez sur *Add*
. Parcourez et sélectionnez l'emplacement des certificats racine et intermédiaire Entrust. Le certificat est ajouté dans un panneau sous *certificats racines de confiance*. Une fois les certificats installés, une OVA peut être vérifiée et déployée.



NOTE: Si l'OVA téléchargée n'est pas falsifiée, la colonne *Publisher* affiche *certificat approuvé*.
