---
permalink: scv60_releasenotes_60_whats_new.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, scv, 6.0, 6.0.1' 
summary: Découvrez les nouvelles fonctionnalités disponibles dans le plug-in SnapCenter pour VMware vSphere 6.0. 
---
= Nouveautés du plug-in SnapCenter pour VMware vSphere 6.0
:allow-uri-read: 


[cols="30%,70%"]
|===
| Mise à jour | Description 


 a| 
https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_concepts_overview.html["Prise en charge du protocole NVMe over TCP"]
 a| 
Le plug-in SnapCenter pour VMware vSphere 6.0 prend désormais en charge le protocole NVMe over TCP pour les datastores VMFS.

Vous n'avez pas besoin de matériel supplémentaire pour déployer le protocole NVMe over TCP, ce qui vous rend plus simple et plus économique.

Tout comme iSCSI, les datastores VMFS avec protocole NVMe over TCP peuvent utiliser n'importe quelle carte réseau et switch ethernet, et prendre en charge toutes les opérations standard telles que la sauvegarde, la restauration, le montage, la connexion et le détachement.



 a| 
https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_create_backup_policies_for_vms_and_datastores.html["Prise en charge de la synchronisation active SnapMirror"]
 a| 
Vous pouvez désormais utiliser le plug-in SnapCenter pour VMware vSphere pour configurer les fonctionnalités de synchronisation active de SnapMirror, telles que l'objectif de point de récupération (RPO) nul, l'objectif de délai de restauration (RTO) et le basculement transparent des applications.

La synchronisation active SnapMirror est prise en charge uniquement pour les datastores VMFS.

|===