---
permalink: scv_releasenotes_whats_new.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, scv, 6.2' 
summary: Découvrez les nouvelles fonctionnalités disponibles dans SnapCenter Plug-in for VMware vSphere 6.2. 
---
= Nouveautés du SnapCenter Plug-in for VMware vSphere 6.2
:allow-uri-read: 


[role="lead"]
Découvrez les nouvelles fonctionnalités disponibles dans SnapCenter Plug-in for VMware vSphere 6.2.

La version SnapCenter Plug-in for VMware vSphere 6.2 ajoute la prise en charge de la sauvegarde et de la récupération des machines virtuelles (VM) sur les banques de données VMFS pour les systèmes ASA r2 exécutant ONTAP 9.17.1 ou version ultérieure.  Avec cette version, vous pouvez effectuer les opérations suivantes pour les machines virtuelles, les banques de données et le format de disque de machine virtuelle (VMDK) sur les systèmes ASA r2 :

* Groupes de cohérence des provisions pour la protection primaire
* Effectuer des sauvegardes basées sur des groupes de cohérence
* Utiliser des groupes de cohérence hiérarchiques (disponibles avec ONTAP 9.17.1 et versions ultérieures)
* Exécuter des workflows de clonage
* Exécuter des flux de travail de restauration
* Fournir une protection secondaire lors de la création ou de la modification de groupes de ressources (disponible avec ONTAP 9.16.1 et versions ultérieures)


À compter de cette version, le SnapCenter Plug-in for VMware vSphere prend en charge les systèmes de stockage Amazon FSxN pour NetApp ONTAP exécutant la version 9.10 ou ultérieure.
